### ISSUE TITLE
SSH ERROR!

### ISSUE THREAD

**Issue by mevam** [HenryCook/vagrant-kubernetes#1]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by HenryCook** [comment]
How weird.

What version of Vagrant are you running, and could you run `vagrant box update` as maybe the Ubuntu box is out of date.

Also worth updating your Virtualbox to the latest version.

**Comment by HenryCook** [comment]
@mevam, are you still experiencing vagrant ssh issues?

**Comment by HenryCook** [comment]
I am closing this issue as I haven't heard anything back regarding the issue, but please do re-open if the problem persists.

As a side note I have enforced a required version of Vagrant to hopefully remedy this (see commit 8469c12).
